name: MusicPlayer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutterfire:
  flutter:
    sdk: flutter
#  camera: ^0.9.4
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/logo.png
